### ISSUE TITLE
능력자 1.9.0 마지막 업데이트 플러그인 활성이 안 됩니다.

### ISSUE THREAD

**Issue by sasipchilbeon** [DayBreak365/AbilityWar#16]
플러그인을 넝었는데

[AbilityWar] Enabling AbilityWar v1.9.1
《AbilityWar》플러그인이 지원하지 않는 버전을 이용하고 있습니다.

라고 뜨면서 플러그인이 비활성화되었습니다.
분명 1.9.1이 아닌 1.9.0의 버전인 플러그인을 넣었는데 활성화가 안 되네요..
해결해 주세요.

**Comment by DayBreak365** [comment]
능력자 v1.9.0 릴리즈 파일에 제가 실수로 v1.9.1 릴리즈 파일을 넣어뒀었네요.
파일 변경해뒀으니 다시 다운로드 해서 적용하시면 될 것 같습니다.

**Comment by sasipchilbeon** [comment]
좋은 플러그인 만들어주셔서 감사합니다.저번 주에 처음 접해봤었는데 정말 재밌습니다삼성 갤럭시 스마트폰에서 보냈습니다.
-------- 원본 이메일 --------발신: DayBreak <notifications@github.com> 날짜: 19/7/26  오후 10:42  (GMT+09:00) 받은 사람: DayBreak365/AbilityWar <AbilityWar@noreply.github.com> 참조: sasipchilbeon <sasipchil@gmail.com>, Author <author@noreply.github.com> 제목: Re: [DayBreak365/AbilityWar] 능력자 1.9.0 마지막 업데이트 플러그인 활성이 안 됩니다. (#16) 능력자 v1.9.0 릴리즈 파일에 제가 실수로 v1.9.1 릴리즈 파일을 넣어뒀었네요.

파일 변경해뒀으니 다시 다운로드 해서 적용하시면 될 것 같습니다.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/DayBreak365/AbilityWar/issues/16?email_source=notifications\u0026email_token=AMW32QPRZ6HC7KHHNIXHW7TQBL5NZA5CNFSM4IHAYTW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD24UFCY#issuecomment-515457675",

"url": "https://github.com/DayBreak365/AbilityWar/issues/16?email_source=notifications\u0026email_token=AMW32QPRZ6HC7KHHNIXHW7TQBL5NZA5CNFSM4IHAYTW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD24UFCY#issuecomment-515457675",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
