### ISSUE TITLE
v1.9.0 AbilityWar 플러그인 업데이트 문의

### ISSUE THREAD

**Issue by sasipchilbeon** [DayBreak365/AbilityWar#17]
1.11.2 서버를 사용하고 있고 능력자 플러그인 v1.9.0 을 사용하고 있는데
1.9.1로 업데이트 하라는 문구가 계속 뜨는데 없애는 방법좀 알려주실 수 있나요?

**Comment by DayBreak365** [comment]
없애는 방법은 존재하지 않습니다.
다만 해당 문구는 OP 권한을 가지고 있는 플레이어들에게만 출력되며,
게임이 시작됐을 경우 출력되지 않기 때문에 방해가 되지는 않으리라 생각됩니다.
