### ISSUE TITLE
ability war 사용시 moved too quickly!뜨며 강제종료되는 현상

### ISSUE THREAD

**Issue by TaeDDin** [DayBreak365/AbilityWar#40]
[2020-03-14-8.log.gz](https://github.com/DayBreak365/AbilityWar/files/4332610/2020-03-14-8.log.gz)
[crash-2020-03-14_19.59.22-server.txt](https://github.com/DayBreak365/AbilityWar/files/4332612/crash-2020-03-14_19.59.22-server.txt)

아래는 스피곳 버킷 1.12.2로 열었을때고 위에는 크래프트버킷 1.12.2로 열었을때의 크래쉬와 로그입니다. 정확한 이유는 잘모르겠으나 AbilityWar 플러그인을 빼면 이런 증상 1도 없습니다.

[2020-03-14-6.log.gz](https://github.com/DayBreak365/AbilityWar/files/4332613/2020-03-14-6.log.gz)
[crash-2020-03-14_19.45.58-server.txt](https://github.com/DayBreak365/AbilityWar/files/4332611/crash-2020-03-14_19.45.58-server.txt)

**Comment by DayBreak365** [comment]
사용중이신 Craftbukkit `git-Bukkit-e60fc34` 버전에서 램 1GB 할당 후 구동을 해본 결과, 게임 실행 및 진행 중 아무 문제도 발생하지 않았습니다. (운영체제: **Windows 10**, Java 버전: **13**)
크래쉬를 확인해보니 리눅스 운영체제를 사용 중이신걸로 보이는데, 저와 다른 운영체제를 사용중이셔서 제가 테스트 해본 결과와 다르게 동작할 가능성이 있습니다.

아래 방법들을 시도해보시길 바랍니다.
- 서버에 더 많은 램을 할당해보세요.
- 월드 전체 초기화를 시도해보세요.
- 스피곳 대신 페이퍼스피곳 사용을 시도해보세요. ([클릭](https://papermc.io/downloads))

계속 문제가 발생하다면 추가 답글 부탁드립니다.

**Comment by DayBreak365** [comment]
일단 이 이슈는 닫아두도록 하겠습니다.
혹시 문제가 추가로 발생한다면 re-open 해주시길 바랍니다.
