### ISSUE TITLE
능력 활성화/비활성화

### ISSUE THREAD

**Issue by anberry87** [DayBreak365/AbilityWar#49]
## 문제점
Config 에서 능력을 활성화/비활성화 되면 좋겠습니다.
## 개선 방안
예:
어떤능력 = true
또다른_능력 = false
또또다른_능력 = true

이러면 능력 추첨에서 "어떤 능력"과"또또다른 능력"이 나오고
"또다른_능력" 은 나오지 않게.

**Comment by DayBreak365** [comment]
이 기능은 이미 존재하는 기능입니다. (능력 블랙리스트, /aw config blacklist)
