### ISSUE TITLE
팀 게임에서 마인크래프트 커맨드로 팀을 감지할 수 없음

### ISSUE THREAD

**Issue by shs3182ym** [DayBreak365/AbilityWar#54]
원래 플러그인 팀이랑 마인크래프트 팀이랑 별개인가요? 코드에는 마인크래프트 팀 등록하는 게 있긴 하던데

**Comment by DayBreak365** [comment]
능력자 플러그인에서 서버에서 기존에 사용중이던 스코어보드와의 혼선을 방지하기 위해 매 판마다 새로운 스코어보드를 만들어 사용합니다. 메인 스코어보드를 사용하는게 아니기 때문에 커맨드로 팀을 감지하는건 힘들 것 같습니다.\

플러그인을 사용하신다면 게임에서 사용하는 스코어보드를 따로 받아오실 수 있습니다.

**Comment by shs3182ym** [comment]
그러면 그 부분만 뜯어서 바꾸면 사용이 가능한가요?

**Comment by DayBreak365** [comment]
https://github.com/DayBreak365/AbilityWar/blob/master/modules/Plugin/src/daybreak/abilitywar/game/module/ScoreboardManager.java

이 클래스를 수정해주시면 아마도 사용 가능할 것 같습니다만 가능하다면 그냥 플러그인을 이용해서 추가 개발하는걸 추천드립니다.
