### ISSUE TITLE
애드온 Skabi 1.12.2 작동안됨

### ISSUE THREAD

**Issue by dlstjdghd** [Daybreak365/AbilityWar#57]
## 문제점
제가 1.12.2에 Skabi라는 애드온을 깔려고하는데 오류가 뜨면서 깔리지 않습니다. 혹시 개발이 중지된건가요?

**Comment by Daybreak365** [comment]
직접 테스트 해본 결과 문제 없이 설치되는 것으로 보입니다. 오류 내역을 보내주실 수 있을까요

**Comment by dlstjdghd** [comment]
네네

**Comment by dlstjdghd** [comment]
회사에 있어서 회사 끝나면 오류 보내드리겠습니다

**Comment by dlstjdghd** [comment]
안되는줄 알았더니 skabi 되네요.. 죄송합니다 꾸벅 ㅡ-ㅡ
