### ISSUE TITLE
빈 상태로 플러그인을 빌드할 때 일부 의존적 패키지를 가져올 수 없습니다

### ISSUE THREAD

**Issue by JeonDohyeon** [Daybreak365/AbilityWar#58]
## 문제점
플러그인에 기능을 추가해 사용하려고 git clone을 통해 가져와, 테스트도 할 겸 빌드를 돌렸는데 `maven-shade-plugin:3.3.0-SNAPSHOT` 파일을 다운받을 수 없다고 표시되며 빌드가 중단됩니다.
아파치에서 스냅샷 파일을 서버에서 날려먹은 것도 한 몫 했지만, 해당 파일을 찾아 로컬 레포지트리를 건드리고 나서야 빌드가 가능했습니다.
(빌드에 이용되는 소스 내 위치는 잘 몰라서, 또 다른 프로젝트에서 쓸 가능성이 있다고 생각해 로컬 레포에 집어넣었습니다)
### 문제 재현 방법
1. 새로운 빌드 환경에서, BuildTools를 이용해 필요한 파일을 생성해 적용합니다.
2. 최신 master 레포지트리를 빌드합니다.
## 개선 방안
*사실 이 경우에선 개선 방안이라기보단 해결 방안이 더 맞겠네요*
1. Ability War에서 이용하는 maven 스냅샷 파일을 maven 빌드 과정에서 이용할 수 있는 별도의 위치에 백업해 소스 코드에 제공
2. 아파치 쪽에서 3.3.x를 공개하는 방안
3. 소스 코드에 해당 파일을 포함해 제공(라이센스: 아파치 2.0, 2008년판 / 파일 버전: Java JAR 1.7)

**Comment by JeonDohyeon** [comment]
- 저기 태그해서 올린 거 지금 빌드하면서 다시 테스트하고 오타 수정해서 올리겠습니다.

저거 수정한 거 말씀드리자면...
`modules/plugin/pom.xml`에 다음이 추가되었습니다.
```xml
    <pluginRepositories>
        <pluginRepository>
            <!-- 아파치 스냅샷 레포지트리 정보 추가 -->
            <id>apache-snapshot</id>
            <url>https://repository.apache.org/content/groups/snapshots</url>
        </pluginRepository>
    </pluginRepositories>
```

**Comment by Daybreak365** [comment]
감사합니다. 오늘 저녁에 적용해보겠습니다

**Comment by Daybreak365** [comment]
자바 상위버전 호환을 위해 maven-shade-plugin 베타 버전 사용 중이었는데,
정식 버전으로 릴리즈 됨에 따라 해결될 것으로 보입니다.
