### ISSUE TITLE
1.18.1 지원 버전 추가 예정 있으신가요

### ISSUE THREAD

**Issue by cdyme** [Daybreak365/AbilityWar#59]
이전 버전은 몇개월전 논란이있던 log4j가 걱정되서 패치된 1.18.1에서 서버를 열고싶은데 혹시 추가 에정 있으신가요

**Comment by Daybreak365** [comment]
Paper 사용 시 1.18.1에서 플러그인 최신 버전 정상 작동했던 것으로 기억하는데 한 번 확인해주실 수 있을까요

**Comment by cdyme** [comment]
> Paper 사용 시 1.18.1에서 플러그인 최신 버전 정상 작동했던 것으로 기억하는데 한 번 확인해주실 수 있을까요

제가 페이퍼 1.18.1 하다가 비활성화되서 17버전으로 내려서 했습니다 

다시해봐도 플러그인이 지원하지 않은 버전입니다. 플로드인이 비활성화 되었습니다.하고 작동이안되네요

**Comment by Daybreak365** [comment]
생각해보니 1.17까지만 지원 가능하게 해뒀었네요
1.18.1 호환 패치 진행해보도록 하겠습니다

**Comment by ldhgogogo** [comment]
현재 1.19까지 버전이 새로 나왔는데, 이 부분에 대해 버전 지원이 가능하게 패치가 될까요?

**Comment by Daybreak365** [comment]
@ldhgogogo 
1.18 지원에 기술적인 문제가 있어 지연된 것도 있고, 제가 시간이 부족해서 진행에 어려움도 있네요...
7, 8월 즈음에 널널해지면 다른 애드온 개발자분이 알려주신 방법으로 한 번 시도해보도록 하겠습니다

**Comment by ldhgogogo** [comment]
서버 버킷 자바 버전에 대해 여러가지 불편함이 있어서 한번 남겨보았더니 활동하고 계셔서 정말 기쁠 따름입니다.
지원에 대한 생각이 있다는 것만으로도 감사합니다 !

**Comment by Daybreak365** [comment]
@ldhgogogo @cdyme
1.19 호환 패치 완료되었습니다.
