### ISSUE TITLE
그래플링 훅 너프, 카오스 버프

### ISSUE THREAD

**Issue by RainStar12** [Daybreak365/AbilityWar#61]
## 문제점
그래플링 훅과 카오스는 C등급과 S등급만큼의 격차가 존재하는데
둘이 같은 L급 선상에 두는 것은 잘못되었습니다
카오스를 S급으로 등급 재조정하거나 버프하고
그래플링 훅은 어떻게던 너프해야 한다고 봅니다

아 좀 해줘 좀
## 개선 방안
카오스
단순명료하게 S급으로 내리는 방법도 있고
L급에 위치하게 하려면 지속 시간과 범위를 버프해야 할듯
수치 버프 말고 리워크하는 방식의 버프도 ㄱㅊ

그래플링 훅
적에게 걸어 급습 효과가 자동 발동된다면 기절 시간을 줄여도 된다고 봄

**Comment by Daybreak365** [comment]
완료
