### ISSUE TITLE
1.20은 아직 지원을 안하는건가요?

### ISSUE THREAD

**Issue by qwer-v** [Daybreak365/AbilityWar#64]
1.20용 craftbukkit dependency를 추가해서 빌드하면 되려나요
제가 플러그인 개발을 잘 몰라서 질문드립니다.

**Comment by Daybreak365** [comment]
1.19.4 및 1.20 지원 과정에서 문제가 발생해서 지원하지 못하고 있습니다.
추후 지원하게 된다면 안내해드리겠습니다.
